/*
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

func fibonacci(until: Int) -> Int {
    var result: [Int] = []
    var first = 0
    var next = 1
    
    while first < until {
        let sum = first + next
        first = next
        next = sum
         
        if sum > until {
            break
        }
        
        if sum % 2 == 0 {
            result.append(sum)
        }
        
    }
    print(result)
    return result.reduce(0, +)
}

print(fibonacci(until: 4000000))
